### ISSUE TITLE
Button '完成' becomes unclickable.

### ISSUE THREAD

**Issue by OIdiotLin** [delbertbeta/homework-uploader#2]
:disappointed: 

With too many items in the list, UI elements are getting messy and the FINISH button unclickable.

![x](https://user-images.githubusercontent.com/8947243/40706510-a2c481e4-6420-11e8-8cc0-25f49ffe3c95.png)

**Comment by delbertbeta** [comment]
哇你怎么优秀到闪耀啊 kirakira的
