### ISSUE TITLE
homework-tip is NOT scrollable

### ISSUE THREAD

**Issue by OIdiotLin** [delbertbeta/homework-uploader#4]
## bug

homework-tip is **NOT scrollable**, though the scrollbar is shown.

I cannot drag or scroll.

## screenshot

![image](https://user-images.githubusercontent.com/8947243/44921864-534b7380-ad76-11e8-8dcf-5767a8791ad3.png)

## environment

Google Chrome: 68.0.3440.106 (x64)

## p.s.

zsynb!

**Comment by delbertbeta** [comment]
Already located issue, fixing.

**Comment by delbertbeta** [comment]
Fixed. Thanks.
